global using AutoFixture;
global using FluentAssertions;
global using FluentAssertions.Execution;
global using Frcs6.Extensions.Caching.MongoDB.Internal;
global using Frcs6.Extensions.Caching.MongoDB.Test.Base;
global using Microsoft.Extensions.Caching.Distributed;
global using MongoDB.Driver;
global using Moq;
global using Xunit;