name: 'Code Analysis'

on:
  push:
    branches: [ 'main' ]
    tags: [ '*' ]
    paths-ignore: [ '**.md' ]

jobs:
  analysis:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Code Analysis
      uses: dotnet/code-analysis@latest
      with:
        solution: Frcs6.Extensions.Caching.MongoDB.sln
        build-breaking: true
        all-categories: all
