name: 'Code Analysis'

on:
  push:
    branches: [ 'main' ]
    tags: [ '*' ]
    paths-ignore: [ '**.md' ]

jobs:
  build_and_test:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['8.0']
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Code Analysis
      uses: dotnet/code-analysis@v1
      with:
        solution: Frcs6.Extensions.Caching.MongoDB.sln
        build-breaking: true
        all-categories: all