name: 'Stryker'

on:
  workflow_dispatch:
    branches: [ 'main' ]

jobs:
  stryker:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Restore tools
      run: dotnet tool restore

    - name: Stryker
      run: dotnet stryker -O ./artifact-stryker

    - name: Upload artifact
      uses: actions/upload-artifact@v4.1.0
      with:
        name: stryker
        path: artifact-stryker/reports/mutation-report.html