name: 'Stryker'

on:
  # push:
  #   branches: [ 'main' ]
  #   paths-ignore: [ '**.md' ]
  workflow_dispatch:
    branches: [ 'main' ]

jobs:
  stryker_mutator:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Restore tools
      run: |
        dotnet tool restore

    - name: Stryker
      run: |
        dotnet stryker \
          -O ./artifact-stryker \
          -r 'dashboard' \
          --dashboard-api-key "${{ secrets.STRYKER_API_KEY }}" \
          -v ${{ github.ref_name }}
